# Generated by Django 4.1 on 2022-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_result_stackmodel_new_stackmodel_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackmodel',
            name='new',
        ),
        migrations.RemoveField(
            model_name='stackmodel',
            name='old',
        ),
    ]
