# Generated by Django 4.1 on 2022-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_stackmodel_new_remove_stackmodel_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackmodel',
            name='new',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stackmodel',
            name='old',
            field=models.TextField(blank=True, null=True),
        ),
    ]
