# Generated by Django 4.1 on 2022-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_stackmodel_new_stackmodel_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackmodel',
            name='new',
        ),
        migrations.RemoveField(
            model_name='stackmodel',
            name='old',
        ),
        migrations.AddField(
            model_name='operation',
            name='new',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='old',
            field=models.TextField(blank=True, null=True),
        ),
    ]
